nnabla_context:
  context: cudnn
  device_id: 0
  type_config: float

train:
  # The eps added to prevent nan
  eps: 1e-12
  # The learning rate for the network
  learning_rate: 0.00005
  # decay value for ExponentialMovingAverage
  decay: 0.99
  # The beta1 parameter for the Adam optimizer
  beta: 0.9
  # The eps parameter for the Adam optimizer
  adameps: 1e-8
  # The max iteration of the training
  max_iter: 900000
  # The frequency of saving images
  save_freq: 10000

  # The number of the rnn recurrent length
  rnn_n: 10
  # Batch size of the input batch
  batch_size: 4
  # Whether random flip data augmentation is applied
  flip: True
  # Whether perform the random crop
  random_crop: True
  # True for Tecogan training False for FRVSR training
  tecogan: True
  # Whether use constant moving first frame randomly
  movingFirstFrame: True
  # The crop size of the training image
  crop_size: 32
  # Number of residual blocks in the generator 10 for FRVSR and 16 for tecogan
  num_resblock: 16
  # If provided, the training will be resumed from the provided checkpoint
  checkpoint: False # It can be either False or path for checkpoint. Ex : model/checkpoint_100000.json
  # The weight of generator will be loaded as an initial point
  pre_trained_frvsr_weights: ./FRVSR_NNabla_model.h5
  # path to pre-trained weights for the vgg19
  vgg_pre_trained_weights: ./vgg_tf_2_nnabla.h5

gan:
  # The ratio between content loss and adversarial loss
  ratio: 0.01
  # The starting ratio for the temporal adversarial loss
  dt_ratio_0: 1.0
  # An adaptive balancing for Discriminators
  d_balance: 0.4
  # factor of dt crop
  crop_dt: 0.75
  # The scaling factor for the VGG perceptual loss, disable with negative value
  vgg_scaling: 0.2
  # factor of pingpong term, works only when pingpong is True
  pp_scaling: 0.5
  
data:
  # The directory of the video input data, for training
  input_video_dir: ./TecoGAN/TrainingDataPath/
  # The pre of the directory of the video input data
  input_video_pre: scene
  # The starting index of the video directory
  str_dir: 2000
  # The ending index of the video directory
  end_dir: 2249
  # The ending index of the video directory
  max_frm: 119
  # The output directory of the trained model
  output_dir: model
